### ISSUE TITLE
无法获取部分音乐播放链接

### ISSUE THREAD

**Issue by wifi-left** [QiuYaohong/kuwoMusicApi#12]
无法获取部分音乐播放链接

**Comment by UPman24** [comment]
找到 app => service => playUrl.ts 替换一下接口，就能同时下载免费和付费歌曲了
```
const BaseService = require('./BaseService')

export default class PlayUrl extends BaseService {
  async getPlayUrl (mid, br = '128kmp3') {
    return this.commonRequest(`http://www.kuwo.cn/api/v1/www/music/playUrl?mid=${mid}&type=convert_url3&br=${br}`)
  }
}
```
`type为 convert_url3 时，免费/付费音乐都可以听`
`br为音质，可选 128kmp3、192kmp3 和 320kmp3`
接口`/kuwo/url?mid=162457325&br=128kmp3`

npm run ci
npm run start
这样就可以了

**Comment by qyhqiu** [comment]
thanks, 根据你的提示已 fix

**Comment by qyhqiu** [comment]
thanks, 根据你的提示已 fix

**Comment by wifi-left** [comment]
哦，还真是，感谢~
我一直以为web端api不能这么搞了，所以用了客户端的api（不过客户端的api倒一直都很稳定，接口都没换）

**Comment by wifi-left** [comment]
更生草的是，客户端api获取到的永远是最高音质...

**Comment by qyhqiu** [comment]
web端播放地址 mv和music之前官方统一了接口，type区分music 和 mv，不过type=convert_url 可以播放付费音乐就不知道了，感谢指点了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QiuYaohong/kuwoMusicApi] 无法获取部分音乐播放链接 (Issue #12)




 
哦，还真是，感谢~
 我一直以为web端api不能这么搞了，所以用了客户端的api（不过客户端的api倒一直都很稳定，接口都没换）
