### ISSUE TITLE
尝试修复一点bug

### ISSUE THREAD

**Issue by wifi-left** [QiuYaohong/kuwoMusicApi#20]
文本删除

**Comment by wifi-left** [comment]
为防止失效，关闭此issue

**Comment by Lichenwei-Dev** [comment]
> 继 #19 Python版本： [kwurl.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12081884/kwurl.zip) `python kwurl.py <类型（flac/mp3）> <id1> [id2...]` 输出为链接（需要GET请求，header包含kw_token（老的那个）） 如：
> 
> ```shell
> python kwurl.py flac 176704915
> ```
> 
> 获得结果：
> 
> ```
> http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmGldi4g47EsqtfDbGsJckckbTQQd2LAgmD7MTRYX0KerEVX6Qg9XjVa1O2jlO+dCjzao1en8aowYA==
> ```
> 
> 然后
> 
> ```shell
> curl "http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmGldi4g47EsqtfDbGsJckckbTQQd2LAgmD7MTRYX0KerEVX6Qg9XjVa1O2jlO+dCjzao1en8aowYA=="
> ```
> 
> 获得结果
> 
> ```ini
> format=flac
> bitrate=2000
> url=http://lu.sycdn.kuwo.cn/ad8440e2de06e0f896c2bdca4f7f087c/64b6a8ac/resource/s1/57/71/2799166738.flac?bitrate$2000&format$flac&type$convert_url2
> sig=12022329596017127605
> rid=260839262
> type=1
> ```
> 
> （Windows下可以写成ini文件方便读取） 如图所示 ![image](https://user-images.githubusercontent.com/63381531/254307462-cfd60fc1-01be-43dc-9a3f-a6fa9962a69b.png)
> 
> 如果得到的链接访问失败，给请求加上如下headers：
> 
> ```
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
> csrf: 96Y8RG5X3X64
> Referer: https://www.kuwo.cn
> ```
> 
> 某个大佬改的php版本： https://github.com/QiuYaohong/kuwoMusicApi/files/12095133/kuwo.zip

这个php应该有问题，测试了几个rid都是越界的（数组）。
rid来自：https://search.kuwo.cn/r.s?pn=0&rn=1&all=%E5%91%A8%E6%9D%B0%E4%BC%A6&ft=music&newsearch=1&alflac=1&itemset=web_2013&client=kt&cluster=0&vermerge=1&rformat=json&encoding=utf8&show_copyright_off=1&pcmp4=1&ver=mbox&plat=pc&vipver=MUSIC_9.1.1.2_BCS2&devid=38668888&newver=1&issubtitle=1&pcjson=0

**Comment by cenguigui** [comment]
某个大佬改的php版本：
https://github.com/QiuYaohong/kuwoMusicApi/files/12095133/kuwo.zip
好像返回的有个歌曲不对

**Comment by wifi-left** [comment]
这个版本是有问题的，等会儿我发个没问题的版本

**Comment by cenguigui** [comment]
> 这个版本是有问题的，等会儿我发个没问题的版本

感谢大佬

**Comment by wifi-left** [comment]
[url.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12332864/url.zip)

**Comment by cenguigui** [comment]
> [url.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12332864/url.zip)

大佬怎么调用啊
之前的那个我是：
// 加上请求headers：
$obj = new MyClass();
// $rid = "5056718";
$rid = isset($_GET['rid']) ? $_GET['rid'] : null;
$downloadUrl = $obj->getDownloadUrlByApp($rid);
$headers = array(
    'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50',
    'csrf: 96Y8RG5X3X64',
    'Referer: https://www.kuwo.cn'
);

$ch = curl_init($downloadUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$response = curl_exec($ch);
curl_close($ch);

// 正则表达式获取url的值
preg_match('/url=(.*?)\s/', $response, $matches);
$url = $matches[1];

echo $url;

**Comment by xs9888** [comment]
有js版的吗？

**Comment by wifi-left** [comment]
没有，因为JS中数组里有元素超过了INT范围导致会出错，我让AI转换了好几次都不行。（顺带一提PHP版本是AI转换的）

**Comment by VeryFar** [comment]
这文件怎么用呢

**Comment by VeryFar** [comment]
这个算法如何封装成一个API调用呢

**Comment by cnstephen** [comment]
> > [url.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12332864/url.zip)
> 
> 大佬怎么调用啊 之前的那个我是： // 加上请求headers： $obj = new MyClass(); // $rid = "5056718"; $rid = isset($_GET['rid']) ? $_GET['rid'] : null; $downloadUrl = $obj->getDownloadUrlByApp($rid); $headers = array( 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50', 'csrf: 96Y8RG5X3X64', 'Referer: https://www.kuwo.cn' );
> 
> $ch = curl_init($downloadUrl); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); $response = curl_exec($ch); curl_close($ch);
> 
> // 正则表达式获取url的值 preg_match('/url=(.*?)\s/', $response, $matches); $url = $matches[1];
> 
> echo $url;

同问

**Comment by cenguigui** [comment]
> > > [url.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12332864/url.zip)
> > 
> > 
> > 大佬怎么调用啊 之前的那个我是： // 加上请求headers： $obj = new MyClass(); // $rid = "5056718"; $rid = isset($_GET['rid']) ? $_GET['rid'] : null; $downloadUrl = $obj->getDownloadUrlByApp($rid); $headers = array( 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50', 'csrf: 96Y8RG5X3X64', 'Referer: https://www.kuwo.cn' );
> > $ch = curl_init($downloadUrl); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); $response = curl_exec($ch); curl_close($ch);
> > // 正则表达式获取url的值 preg_match('/url=(.*?)\s/', $response, $matches); $url = $matches[1];
> > echo $url;
> 
> 同问
> 
> 
> > > [url.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12332864/url.zip)
> > 
> > 
> > 大啊怎么调之前的那个我是：//添加请求头：$obj = new MyClass（）; // $rid =“5056718”; $rid = isset（$_GET['rid']）？$_GET返回'rid']：null; $downloadUrl = $obj->getDownloadUrlByApp（$rid）;$headers = array（'User-Agent：Mozilla/5.0（Macintosh; Intel Mac OS X 10_15_7）AppleWebKit/537.36（KHTML，like Gecko）Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50'，'csrf：96Y8RG5X3X64'，'Referer：[https：//www.kuwo.cn](https://www.kuwo.cn)'）;
> > $ch = curl_init（$downloadUrl）; curl_setopt（$ch，CURLOPT_RETURNTRANSFER，true）; curl_setopt（$ch，CURLOPT_HTTPHEADER，$headers）; $response = curl_exec（$ch）; curl_close（$ch）;
> > // 正则表达式获取url的值 preg_match（'/url=（.*？）\ [1]$url = $matches[1];
> > return $url;
> 
> 同问

已经解决，谢谢

**Comment by wifi-left** [comment]
```php
getMusicUrlUrl(MusicID, MusicType);
```
`MusicType` 可选 `mp3`和`flv`
`MusicID` 就是RID

**Comment by smithlee28** [comment]
> ```
> getMusicUrlUrl(MusicID, MusicType);
> ```
> 
> `MusicType` 可选 `mp3`和`flv` `MusicID` 就是RID

請問這個 python的版本依然可以正常運作嗎?
使用RID = 143341107 無法取得正確的播放網址

**Comment by cenguigui** [comment]
> > ```
> > getMusicUrlUrl(MusicID, MusicType);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `MusicType` 可选 `mp3`和`flv` `MusicID`就是摆脱
> 
> 请问这个python的版本依然可以正常运作吗？ 使用RID = 143341107無法取得正確的播放網址

不能了

**Comment by wifi-left** [comment]
能正常运作。
刚测试

**Comment by wifi-left** [comment]
但是可能这个歌曲不行？

**Comment by cenguigui** [comment]
> 能正常运作。 刚测试

你试试会员歌曲就知道了

**Comment by wifi-left** [comment]
没任何问题。
测试歌曲：冬之花

**Comment by wifi-left** [comment]
等下哈

**Comment by wifi-left** [comment]
看来是修了，昨晚上还是好的

**Comment by wifi-left** [comment]
获取flac链接还能正常播放

**Comment by wifi-left** [comment]
```
H:\myexe\AllMusicDownload>python kwurl.py flac 228908
http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmGldi4g47EsqtfDbGsJckckbTQQd2LAgmD7MTRYX0KerEVX6Qg9XjVar3WB5XBGddNqY0iIU+Qd0Q==

H:\myexe\AllMusicDownload>curl "http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmGldi4g47EsqtfDbGsJckckbTQQd2LAgmD7MTRYX0KerEVX6Qg9XjVar3WB5XBGddNqY0iIU+Qd0Q=="
format=flac
bitrate=2000
url=http://sy.sycdn.kuwo.cn/0739215934fe42f5aa4a42c057dae195/65505ebb/resource/s1/96/9/3483822377.flac?bitrate$2000&format$flac&type$convert_url2
sig=14962903177885333588
rid=260839262
type=1
```
测试歌曲是周杰伦的晴天

**Comment by cenguigui** [comment]
> 获取扩音器链接还能正常播放



> 看来是修了，昨晚上还是好的

有时候可以有时候不行，不稳定了
你可以试试我搭建这个
https://cenguigui.cn/music

**Comment by wifi-left** [comment]
应该是概率性不行，那还是可以的

**Comment by wifi-left** [comment]
我怀疑可能官方现在又改回去了（？）

**Comment by wifi-left** [comment]
建议各位看到的不要宣传出去。免得又失效了

**Comment by wifi-left** [comment]
> > 获取扩音器链接还能正常播放
> 
> > 看来是修了，昨晚上还是好的
> 
> 有时候可以有时候不行，不稳定了 你可以试试我搭建这个 https://cenguigui.cn/music

还有你这个机翻，flac翻译成扩音器了（

**Comment by cenguigui** [comment]
> > > 获取扩音器链接还能正常播放
> > 
> > 
> > > 看来是修了，昨晚上还是好的
> > 
> > 
> > 有时候可以有时候不行，不稳定了 你可以试试我搭建这个 https://cenguigui.cn/music
> 
> 还有你这个机翻，flac翻译成扩音器了（

用php版本没用py的，

**Comment by wifi-left** [comment]
> > > > 获取扩音器链接还能正常播放
> > > 
> > > 
> > > > 看来是修了，昨晚上还是好的
> > > 
> > > 
> > > 有时候可以有时候不行，不稳定了 你可以试试我搭建这个 https://cenguigui.cn/music
> > 
> > 
> > 还有你这个机翻，flac翻译成扩音器了（
> 
> 用php版本没用py的，

两者是同一个东西，php是从python版本让ai转换的

**Comment by cenguigui** [comment]
http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==

我发现这个可以用，酷我换算法

**Comment by shenxingchao** [comment]
> http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==
> 
> 我发现这个可以用，酷我换算法

q用android那个就可以了，666

**Comment by smithlee28** [comment]
> > http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==
> > 我发现这个可以用，酷我换算法
> 
> q用android那个就可以了，666

請問android的那個。 是指哪個??

**Comment by wifi-left** [comment]
> http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==
> 
> 我发现这个可以用，酷我换算法

求一份加密的代码，如果可以，请发到我邮箱：ysy1679682327@hotmail.com
感谢

**Comment by shenxingchao** [comment]
> > http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==
> > 我发现这个可以用，酷我换算法
> 
> 求一份加密的代码，如果可以，请发到我邮箱：[ysy1679682327@hotmail.com](mailto:ysy1679682327@hotmail.com) 感谢
解密就还是原来那个,且用且珍惜，用一个少一个 来自 [link](https://github.com/yhsj0919/music_api/blob/main/lib/api/kuwo/module/song.dart)
```py
willEnc = f"user=0&android_id=0&prod=kwplayer_ar_8.5.5.0&corp=kuwo&newver=3&vipver=8.5.5.0&source=kwplayer_ar_8.5.5.0_apk_keluze.apk&p2p=1&notrace=0&type=convert_url2&br=320kmp3&format=flac|mp3|aac&sig=0&rid={mid}&priority=bitrate&loginUid=0&network=WIFI&loginSid=0&mode=download"

url = f"""http://mobi.kuwo.cn/mobi.s?f=kuwo&q={ KuwoDES.base64_encrypt(KuwoDES,willEnc) }"""
```

**Comment by cnstephen** [comment]
> > http://mobi.kuwo.cn/mobi.s?f=kuwo&q=WdHQrW408QAI6L5nwYw/yvoveAlorFWyOpIo0jgTsGo7Nj9WrEcZU+r0AcylI0/cjJwG/wvVinSPK1t/JB8aYNTGXG2vOGJuWqVwgYX2rI2i/OewHhJBz1+f8ZY6oZR4tPp2XbzWgtvvil8Ko93aG3Tw3qNdXC2bMihICLmHhbSUwqsUlKzMByGSblgEtWcOr3WB5XBGddNqY0iIU+Qd0Q==
> > 我发现这个可以用，酷我换算法
> 
> 求一份加密的代码，如果可以，请发到我邮箱：[ysy1679682327@hotmail.com](mailto:ysy1679682327@hotmail.com) 感谢

php搞一下，😍

**Comment by wifi-left** [comment]
c++的exe版本（仅提供exe版本）：
使用方法：kwurl.exe <类型（MP3)> <ID>
然后会生成一个kwurl.encoded文件，将此二进制文件进行base64编码后，在最前面拼接`http://mobi.kuwo.cn/mobi.s?f=kuwo&q=`
程序语言：C++
编译：G++
编译命令行：`g++ kwurl.cpp -o kwurl.exe -static -pthread`
（至于为什么不直接输出url，是因为c++的base64编码库我找了半天，都会出问题，编码出的文本都不对）
[kwurl.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/14000602/kwurl.zip)

**Comment by cenguigui** [comment]
发现个问题，算法版本，获取不到hr音质，就是4000kflac

但是母带可以，还有看到其他项目的js也可以获取4000kflac，我觉得是算法有问题

**Comment by wifi-left** [comment]
可以看看另一个issue，有更简单的办法，不需要加密
