### ISSUE TITLE
好像无法获取播放链接了，报错

### ISSUE THREAD

**Issue by duskcouple** [QiuYaohong/kuwoMusicApi#4]
![image](https://user-images.githubusercontent.com/26564245/140609010-459026a2-ed21-4396-a193-9447f336b301.png)

**Comment by qyhqiu** [comment]
这个情况已经修复好了， 音乐播放地址 和 视频播放地址 统一使用一个接口了 通过传type类型就好了

![image](https://user-images.githubusercontent.com/51219225/140613187-059a1ed9-1c6c-4237-801a-7b36c1f5ed69.png)

**Comment by duskcouple** [comment]
收到，大佬牛逼
