### ISSUE TITLE
专辑 (album) 音乐列表的接口?

### ISSUE THREAD

**Issue by aguang-xyz** [QiuYaohong/kuwoMusicApi#5]
您好～

我看到文档里有通过 Playlist ID 获取音乐列表的接口 `/kuwo/musicList?pid=1082685104`，但是没有找到通过 Album ID 获取音乐列表的接口。

**Comment by qyhqiu** [comment]
感谢你的反馈，新增了歌手专辑 albumId  获取音乐列表的接口

![image](https://user-images.githubusercontent.com/51219225/141475179-5cb3e93d-7a1c-48b0-a28b-0a008590e773.png)

**Comment by aguang-xyz** [comment]
Awesome!
